include:
  - "app/**/*.rb"
  - "config/**/*.rb"
  - "lib/**/*.rb"
exclude:
  - "spec/**/*"
  - "test/**/*"
  - "vendor/**/*"
  - ".bundle/**/*"
# Bağımlılıkları taramayı tamamen kestik:
require: []
plugins:
  - rails
reporters:
  - rubocop
